apiVersion: v1
kind: ReplicationController
metadata:
  name: employee
spec:
  replicas: 5
  selector:
    app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - image: agrim/lb-employee:v2
          imagePullPolicy: IfNotPresent
          name: employee
          ports:
            - containerPort: 8000
          env:
            - name: ADDR
              value: :8000
                